spring.datasource:
  url: jdbc:h2:./camunda-db;DB_CLOSE_DELAY=-1;MVCC=TRUE;DB_CLOSE_ON_EXIT=FALSE
  username: sa
  password: sa
spring.h2.console.enabled: true
camunda.bpm:
  default-serialization-format: application/json
  admin-user:
    id: demo
    password: demo
    firstName: Demo
    email:
  filter:
    create: All tasks
server.port: 8080
exception:
  requesternotfound:
    message: The requester provided was not found in Camunda BPM
erp:
  rest:
    timeout: 60000
    url: http://localhost:8081
    approver-service:
      base-path: /common/approvers
    invoice-service:
      base-path: /accounts-payable/invoices
    email-service:
      base-path: /notification/emails
templates:
  email: er-type-email-template.ftl
  subject: er-type-email-subj-template.ftl
  type-variable: type
org.camunda.bpm.engine.persistence:
  logging-level: debug